 /******************************************************************************
 * Module: ULTRASONIC SENSOR
 *
 * File Name: ultrasonic_sensor.c
 *
 * Description: Source file for the ULTRASONIC driver
 *
 * Author: Mostafa Mahmoud
 *
 * Group: 71
 *******************************************************************************/

#include <util/delay.h>
#include "ultrasonic_sensor.h"
#include "icu.h"

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

/* Volatile --> Prevent Compiler Optimization on these global variables
   Static   --> To limit the scope of this global variables from SW scope to File Scope
                To prevent sharing this resource with unwanted Modules */

volatile static uint8 g_edgeCount = 0;
volatile static uint16 g_echo_HighTime = 0;

/*******************************************************************************
 *                        Static Functions Prototypes                          *
 *******************************************************************************/

static void Ultrasonic_Trigger(void);

/*******************************************************************************
 *                           Functions Definitions                             *
 *******************************************************************************/

/* Description:
      • Initialize the ICU driver as required.
      • Setup the ICU call back function.
      • Setup the direction for the trigger pin as output pin through the GPIO driver.
*/
void Ultrasonic_init(void)
{
	/* The ICU is configured with frequency F_CPU/8
	 * and Initially to detect the raising edge as the first edge
	 */
	ICU_ConfigType config = {FCPU_8,RISING};

	ICU_init(&config);

	/* Setup function (Ultrasonic_edgeProcessing) as ICU call back function */
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* Setup PC5 (TRIGGER pin) as O/P pin */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
}


/* Description:
     • Send the Trigger pulse to the ultrasonic.
*/
static void Ultrasonic_Trigger(void)
{
	/* Transmit trigger pulse of at least 10 us to the HC-SR04 Trigger Pin */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);

	_delay_us(TRIGGER_PULSE_DURATION);

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}


/* Description
      • Send the trigger pulse by using Ultrasonic_Trigger function.
      • Start the measurements by the ICU from this moment.
   Return:
      • The measured distance in Centimeter.
*/
uint16 Ultrasonic_readDistance(void)
{
	/* Sending the trigger pulse by using Ultrasonic_Trigger function	 */
	Ultrasonic_Trigger();

	/* Calculation (distance in cm)

       Sound velocity = 340.00 m/s = 34000 cm/s

     * As Signal travels from HCSR04 to object and returns to the module HCSR04

	   The distance of Object (in cm) = (340000 * Time)/2
                                      = 17000 * Time

	 * As an internal 8MHz oscillator frequency is selected for ATmega32, with Prescaler F_CPU/8 for timer frequency.
	 * Then F(timer) = FCPU/8 = 1 MHZ ---> T(timer) = 1us.

	   Distance = 17000 x (TIMER value) x 1 x 10^-6 cm
                = 0.017 x (TIMER value) cm

	 * Note TIMER VALUE is the pulse width time calculated by the ICU
	 */
	return (0.017 * g_echo_HighTime);
}


/* Description
      • This is the call back function called by the ICU driver.
      • This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;

	if (g_edgeCount == 1)
	{
		/* Clear the timer counter register to start measurements from the first detected rising edge */
		ICU_clearTimerValue();

		/* Detect falling edge at the Echo pin */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the high time (pulse time) generated by the ultrasonic sensor */
		g_echo_HighTime = ICU_getInputCaptureValue();

		/* Detect falling edge at the Echo pin */
		ICU_setEdgeDetectionType(RISING);

		/* Clear the timer counter register to start measurements again */
		ICU_clearTimerValue();

		g_edgeCount = 0;
	}
}




