 /******************************************************************************
 * Module: ULTRASONIC SENSOR
 *
 * File Name: ultrasonic_sensor.h
 *
 * Description: Header file for the ULTRASONIC driver
 *
 * Author: Mostafa Mahmoud
 *
 * Group: 71
 *******************************************************************************/

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include "std_types.h"
#include "gpio.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define ULTRASONIC_TRIGGER_PORT_ID     PORTC_ID
#define ULTRASONIC_TRIGGER_PIN_ID      PIN5_ID

#define ULTRASONIC_ECHO_PORT_ID        PORTD_ID
#define ULTRASONIC_ECHO_PIN_ID         PIN6_ID

#define TRIGGER_PULSE_DURATION         10

/*******************************************************************************
 *                            Functions Prototypes                              *
 *******************************************************************************/


/* Description:
      • Initialize the ICU driver as required.
      • Setup the ICU call back function.
      • Setup the direction for the trigger pin as output pin through the GPIO driver.
*/
void Ultrasonic_init(void);


/* Description
      • Send the trigger pulse by using Ultrasonic_Trigger function.
      • Start the measurements by the ICU from this moment.
   Return:
      • The measured distance in Centimeter.
*/
uint16 Ultrasonic_readDistance(void);


/* Description
      • This is the call back function called by the ICU driver.
      • This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_SENSOR_H_ */
